# -*- coding: utf-8 -*-
"""diagramas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z1SCG4m8e_9KgwgapK4EfLl_VjPKPajc
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import chardet

sns.set(style="whitegrid")

# -------------------------------
# Función para leer CSV con encoding automático
# -------------------------------
def load_csv_autoencoding(path):
    with open(path, 'rb') as f:
        result = chardet.detect(f.read())
    encoding = result['encoding']
    print(f"📂 Leyendo {path} con encoding detectado: {encoding}")
    return pd.read_csv(path, encoding=encoding, on_bad_lines="skip")


# ==========================
# 1. Dataset de Netflix
# ==========================
df_netflix = load_csv_autoencoding("Netflix Dataset.csv")

plt.figure(figsize=(6,4))
df_netflix["Category"].value_counts().plot(kind="bar", color=["red", "blue"])
plt.title("Netflix - Películas vs Series")
plt.xlabel("Categoría")
plt.ylabel("Cantidad")
plt.show()


# ==========================
# 2. Dataset Airlines Flights
# ==========================
df_airlines = load_csv_autoencoding("airlines_flights_data.csv")

print("Columnas de Airlines:", df_airlines.columns.tolist())

# Un solo gráfico: Top 10 aerolíneas con más vuelos
if "airline" in df_airlines.columns:
    plt.figure(figsize=(10,5))
    df_airlines["airline"].value_counts().head(10).plot(kind="bar", color="skyblue")
    plt.title("Airlines - Top 10 Aerolíneas con más vuelos")
    plt.xlabel("Aerolínea")
    plt.ylabel("Cantidad de vuelos")
    plt.show()


# ==========================
# 3. Dataset Cars
# ==========================
df_cars = load_csv_autoencoding("Cars Datasets 2025.csv")

print("Columnas de Cars:", df_cars.columns.tolist())

# Un solo gráfico: Top 10 compañías con más modelos
plt.figure(figsize=(10,5))
df_cars["Company Names"].value_counts().head(10).plot(kind="bar", color="orange")
plt.title("Cars - Top 10 compañías con más modelos")
plt.xlabel("Compañía")
plt.ylabel("Cantidad de modelos")
plt.show()